DELIMITER $$

CREATE TRIGGER `Item_INSERT` BEFORE INSERT ON `Item`
FOR EACH ROW BEGIN
    SET ROW.Created = NOW();
END$$


CREATE TRIGGER `Tag_INSERT` BEFORE INSERT ON `Tag`
FOR EACH ROW BEGIN
    SET ROW.Created = NOW();
END$$


CREATE TRIGGER `Date_INSERT` BEFORE INSERT ON `Date`
FOR EACH ROW BEGIN
    SET ROW.Date = NOW();
END$$

DELIMITER ;

